[build]
  functions="backend-output/functions" 
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
[dev]
  targetPort = 5173